apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: microservices-quiz-app
build:
  artifacts:
    # auth
    - image: auth-img
      context: auth
      docker:
        dockerfile: Dockerfile
    - image: auth-img-dev
      context: auth
      docker:
        dockerfile: Dockerfile.dev
    # quiz
    - image: quiz-img
      context: quiz
      docker:
        dockerfile: Dockerfile
    # react client
    - image: react-client-img
      context: react-client
      docker:
        dockerfile: Dockerfile
    - image: react-client-img-dev
      context: react-client
      docker:
        dockerfile: Dockerfile.dev
test:
  # auth
  - image: auth-img-dev
    context: auth
    custom:
      # run test in container
      - command: echo $IMAGE && docker run -e CI=true $IMAGE npm test
  # react-client
  - image: react-client-img-dev
    context: react-client
    custom:
      # run test in container
      - command: docker run -e CI=true $IMAGE npm test
manifests:
  rawYaml:
  - auth/k8s/*.yaml
  - react-client/k8s/*.yaml 
  - quiz/k8s/*.yaml
  # - jwt-secret.yaml created manually
  - ingress-srv.yaml

