apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: microservices-quiz-app
build:
  artifacts:
    - image: auth-img
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*.js
            dest: .
    - image: react-client-img
      context: react-client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*.tsx
            dest: .
# test:
#   - image: auth-img
#     context: auth
#     custom:
#       - command: node --version
manifests:
  rawYaml:
  - auth/k8s/*.yml
  - react-client/k8s/*.yml
  - jwt-secret.yml
  - ingress-srv.yml

