apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
  # labels:
  #   app: auth-depl-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-pod-label
  template:
    metadata:
      labels:
        app: auth-pod-label
    spec:
      containers:
      - name: auth-pod
        image: auth-img
        ports:
        - containerPort: 3000
        env:
          - name: MONGO_URI
            value: mongodb://auth-mongo-srv:27017/auth
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth-pod-label
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
