FROM node:18-alpine
WORKDIR /app
COPY ["package.json", "package-lock.json*", "./"]
# use cached production image
RUN npm i --production
COPY . .
# install dev dependencies
RUN npm i
CMD ["npm", "run", "dev"]